version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: clientutils/*
      - linters:
          - lll
        path: envtestutils/*
      - linters:
          - lll
        path: unstructuredutils/*
      - linters:
          - lll
        path: metautils/*
      - linters:
          - lll
        path: kustomizeutils/*
      - linters:
          - lll
        path: configutils/*
      - linters:
          - lll
        path: conditionutils/*
      - linters:
          - lll
        path: testutils/*
      - linters:
          - dupl
        path: cmdutils/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
