run:
  timeout: 10m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "clientutils/*"
      linters:
        - lll
    - path: "envtestutils/*"
      linters:
        - lll
    - path: "unstructuredutils/*"
      linters:
        - lll
    - path: "metautils/*"
      linters:
        - lll
    - path: "kustomizeutils/*"
      linters:
        - lll
    - path: "configutils/*"
      linters:
        - lll
    - path: "conditionutils/*"
      linters:
        - lll
    - path: "testutils/*"
      linters:
        - lll
    - path: "cmdutils/*"
      linters:
        - dupl
linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - ginkgolinter
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused