run:
  concurrency: 4
  timeout: 10m

linters:
  enable:
    - revive
    - ineffassign
    - misspell
    - goimports
    - importas
    - unused
    - ginkgolinter

severity:
  default-severity: error

linters-settings:
  revive:
    severity: error
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: if-return
        disabled: true
